client-sanghyun: Feat/#73 signuppage
codestates-seb/seb40_main_027 pull request #108
Opened 2022-11-21 05:25 UTC by headring

회원가입 페이지 완성했습니다.

2022-11-21 09:35 UTC, jwp9633 requested changes

2022-11-21 09:35 UTC, jwp9633 commented on client/src/App.tsx
> +import SignUp from './pages/SingUp';
`./pages/SingUp` -> `./pages/SignUp`
오타 수정해주세요.

2022-11-21 09:35 UTC, jwp9633 commented on client/src/components/Button/RegisterButton.tsx
> +interface PropType {
`PropType` -> `PropsType`으로 수정하면 어떨까요?

2022-11-21 09:35 UTC, jwp9633 commented on client/src/pages/SignUp.style.tsx
> +  height: 100vh;
height가 100vh여서 Footer 컴포넌트는 스크롤 해야 보입니다.
여백이 충분히 많으니 `height: calc(100vh - 17px);`로 하면 어떨까요?

2022-11-21 09:35 UTC, jwp9633 commented on client/src/pages/SignUp.style.tsx
> +  @media ${theme.mobile} {
모바일 버전 스타일 적용이 안 된 것 같습니다. 확인 부탁드려요.

2022-11-21 09:35 UTC, jwp9633 commented on client/src/pages/SingUp.tsx
> +  const onSumbit = (data: any) => console.log(data);
`onSumbit` -> `onSubmit` 수정 부탁드려요.

2022-11-22 01:53 UTC, skyhanull commented
헤더부분이 너무 내려온 것 같아서 회원가입 폼을 조금 올려주거나 크기를 키워도 좋을 것 같습니다!

2022-11-22 04:45 UTC, headring commented on client/src/App.tsx
> +import SignUp from './pages/SingUp';
오타 수정했습니다

2022-11-22 04:46 UTC, headring commented on client/src/components/Button/RegisterButton.tsx
> +interface PropType {
PropsType으로 변경했습니다

2022-11-22 04:48 UTC, headring commented on client/src/pages/SignUp.style.tsx
> +  height: 100vh;
max-hegiht값으로 1080px주고 일단 calc()써서 뺐습니다. 다만 현재 세로 비율 1080px가 어느 환경에서도 모두 크게 보이는 것 같아서 스크롤이 될 수 밖에 없습니다. 또한 원래 회원가입에는 footer가 존재하지 않습니다.

2022-11-22 04:48 UTC, headring commented on client/src/pages/SignUp.style.tsx
> +  @media ${theme.mobile} {
모바일 동의 쪽이 사라지지 않는 것 해결했습니다

2022-11-22 04:48 UTC, headring commented on client/src/pages/SingUp.tsx
> +  const onSumbit = (data: any) => console.log(data);
오타 수정했습니다

2022-11-22 04:59 UTC, jwp9633 requested changes

2022-11-22 04:59 UTC, jwp9633 commented on client/src/pages/SignUp.style.tsx
> +export const greenTxtBrd = styled.div`
`greenTxtBrd` -> `GreenTxtBrd` PascalCase로 수정 부탁드립니다.

2022-11-22 04:59 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +  const onSumbmit = (data: any) => console.log(data);
`onSumbmit` -> `onSubmit` 오타 수정 부탁드립니다.

2022-11-22 04:59 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +        <form onSubmit={handleSubmit(onSumbmit)}>
`onSumbmit` -> `onSubmit` 오타 수정 부탁드립니다.

2022-11-22 05:04 UTC, headring commented on client/src/pages/SignUp.tsx
> +        <form onSubmit={handleSubmit(onSumbmit)}>
수정했습니다

2022-11-22 05:04 UTC, headring commented on client/src/pages/SignUp.tsx
> +  const onSumbmit = (data: any) => console.log(data);
수정했습니다

2022-11-22 05:04 UTC, headring commented on client/src/pages/SignUp.style.tsx
> +export const greenTxtBrd = styled.div`
수정했습니다

2022-11-22 05:07 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-22 05:08 UTC, merged