client-yoonkyoung: testpage페이지 구현
codestates-seb/seb40_main_027 pull request #109
Opened 2022-11-21 05:26 UTC by skyhanull

2022-11-21 10:12 UTC, jwp9633 requested changes

2022-11-21 10:12 UTC, jwp9633 commented on client/src/components/TestForm/TypeForm.tsx
> +    ' 기능이 먼저다. vs 아니다. 디자인이 먼저다',
16, 17번째 줄 처음에 띄어쓰기를 넣은 이유가 있으실까요?

2022-11-21 10:12 UTC, jwp9633 commented on client/src/components/TestForm/WarningWindow.tsx
> +          <S.WarnContent>이 테스트는 정확한 테스트가 아니므로 주의해주십시오.</S.WarnContent>
모바일 화면에서 18번째 줄 문구가 화면 밖으로 나가 있습니다. 수정 부탁드려요.
![Screenshot 2022-11-21 at 7 02 43 PM](https://user-images.githubusercontent.com/47207736/203022190-168f3323-6bef-41bb-b155-93a08717e2aa.png)

2022-11-21 10:12 UTC, jwp9633 commented on client/src/components/TestForm/TypeForm.tsx
> +            <S.SContentForm>{QuestionList.filter((el, idx) => idx === idNumber)}</S.SContentForm>
질문 길이(질문이 1줄인지, 2줄인지, 3줄인지)에 따라 사진과 보기의 위치가 달라지는데,
질문 길이에 상관없이 사진과 보기의 위치가 고정되어 있다면 UX가 향상될 것 같습니다.

이거는 제 생각이니 적용 안 하시거나 나중에 하셔도 됩니다.

2022-11-21 10:12 UTC, jwp9633 commented on client/src/pages/Test.tsx
> +    <div>
div 요소가 단순히 감싸기 위한 용도라면 `<></>`를 사용해 보면 어떨까요?

2022-11-21 10:12 UTC, jwp9633 commented on client/src/pages/Test.style.ts
> +  height: 100vh;
`height: calc(100vh - 헤더 높이 - 푸터 높이)`로 설정하면 어떨까요?

화면에 여백이 있어서 위처럼 설정하면 스크롤 없이 모든 컴포넌트를 보여줄 수 있을 것 같습니다.

2022-11-21 11:20 UTC, skyhanull commented on client/src/components/TestForm/TypeForm.tsx
> +            <S.SContentForm>{QuestionList.filter((el, idx) => idx === idNumber)}</S.SContentForm>
px로 길이 고정했습니다

2022-11-21 11:21 UTC, skyhanull commented on client/src/pages/Test.tsx
> +    <div>
수정했습니다

2022-11-21 11:26 UTC, skyhanull commented on client/src/components/TestForm/WarningWindow.tsx
> +          <S.WarnContent>이 테스트는 정확한 테스트가 아니므로 주의해주십시오.</S.WarnContent>
폰트크기 줄여서 수정했습니다

2022-11-21 11:33 UTC, skyhanull commented on client/src/App.tsx
> +        <Route path="/user/test" element={<Test />} />
수정했습니다

2022-11-21 11:33 UTC, skyhanull commented on client/package-lock.json
> +
지금 이거 해보려다가 npm i 오류가 발생해서 이거에 대해 사진올려놓겠습니다

2022-11-21 11:33 UTC, skyhanull commented on client/src/components/TestForm/EndForm.tsx
> +      <div className="font-Result-title">결과는?</div>
수정했습니다

2022-11-21 11:36 UTC, skyhanull commented on client/src/components/TestForm/EndForm.style.ts
> +  .font-Result-title {
수정했습니다

2022-11-21 11:36 UTC, skyhanull commented on client/src/components/TestForm/StartForm.style.ts
> +    background-color: var(--greenSub); //마이페이지에 컬러지정해서 이곳에서는 우선 사용
수정했습니다

2022-11-21 11:36 UTC, skyhanull commented on client/src/components/TestForm/TypeForm.tsx
> +  const ViewYesHandelr = () => {
수정했습니다

2022-11-21 11:37 UTC, skyhanull commented on client/src/components/TestForm/TypeForm.tsx
> +  const ViewNoHandelr = () => {
수정했습니다

2022-11-21 11:37 UTC, skyhanull commented on client/src/components/TestForm/TypeForm.tsx
> +    ' 기능이 먼저다. vs 아니다. 디자인이 먼저다',
수정했습니다

2022-11-21 11:39 UTC, skyhanull commented on client/src/components/TestForm/StartForm.tsx
> +  const [isStart, setIsStart] = useState<boolean>(false);
0으로 초기화를 안해도 새로고침시 초기화가 되서 꼭 필요하진 않을 것 같습니다

2022-11-21 11:40 UTC, skyhanull commented on client/src/components/TestForm/StartForm.style.ts
> +    animation: fadein 7s ease-in-out;
이부분은 삭제하려고 한것이라 삭제했습니다

2022-11-21 11:41 UTC, skyhanull commented on client/src/pages/Test.style.ts
> +  height: 100vh;
죄송하지만 제가 푸터높이랑 헤더높이를..?몰라서 어떤식으로 해야할 지 모르겠습니다

2022-11-22 01:17 UTC, jwp9633 commented on client/package.json
> +
수정이 안 된 것 같은데 한 번만 더 확인 부탁드릴게요.

2022-11-22 01:17 UTC, jwp9633 commented on client/package-lock.json
> +
사진 올려주시면 확인해보겠습니다.

2022-11-22 01:21 UTC, jwp9633 commented on client/src/pages/Test.style.ts
> +  height: 100vh;
Header 컴포넌트의 높이는 4rem,
Footer 컴포넌트의 높이는 데스크탑 17px, 모바일 11px 이네요.

2022-11-22 01:37 UTC, headring approved these changes
고생하셨습니다 :)

2022-11-22 01:37 UTC, headring commented on client/src/components/TestForm/TypeForm.tsx
> +const MyComponent = () => {
TypeForm 파일 안에서 다른 이름이 있는 것보다 TypeForm이 더 좋을 듯 합니다

2022-11-22 01:38 UTC, jwp9633 commented on client/src/components/TestForm/StartForm.tsx
> +  const [isStart, setIsStart] = useState<boolean>(false);
새로고침을 하지 않고 다시 테스트하고 싶은 경우가 있을 수도 있으니 추가하는 게 어떨까요?

다른 로직과 연관되어 있어서 구현이 어렵다면 하지 않으셔도 괜찮을 것 같습니다.
말씀하신 대로 새로고침한 상태에서 접근하는 경우가 대부분일 테니까요.

2022-11-22 01:39 UTC, jwp9633 commented on client/src/pages/Test.style.ts
> +  height: 100vh;
적용이 어렵다면 넘어가셔도 괜찮습니다.

2022-11-22 01:39 UTC, headring approved these changes

2022-11-22 01:39 UTC, headring commented on client/src/components/TestForm/EndForm.tsx
> +  const [isNo, setIsNo] = useRecoilState<number>(NoContent);
이 부분은 저희가 구독만 하니까 useRecoilValue를 사용하여 값을 읽기만 하면 어떨까요?

2022-11-22 01:41 UTC, jwp9633 requested changes
이전 리뷰에서 resolved 안 된 것과 상현 님 리뷰 확인해주시면 좋을 것 같습니다.

2022-11-22 01:41 UTC, jwp9633 commented on client/src/components/TestForm/TypeForm.tsx
> +const MyComponent = () => {
저도 동의합니다.

2022-11-22 01:43 UTC, skyhanull commented on client/src/components/TestForm/StartForm.tsx
> +  const [isStart, setIsStart] = useState<boolean>(false);
이건 적어놨다가 제가 다시 만져보겠습니다

2022-11-22 01:48 UTC, skyhanull commented on client/src/pages/Test.style.ts
> +  height: 100vh;
요부분은 제가 나중에 전체페이지 높이 확인해보겠습니다

2022-11-22 02:14 UTC, jwp9633 requested changes

2022-11-22 02:14 UTC, jwp9633 commented on client/package.json
> +
아직 수정이 안 된 것 같습니다.

2022-11-22 02:23 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-22 02:48 UTC, jwp9633 requested changes

2022-11-22 02:48 UTC, jwp9633 commented on client/src/components/TestForm/TypeForm.style.ts
> +  }
이 부분은 삭제해야 될 것 같습니다.

2022-11-22 02:50 UTC, merged

2022-11-22 02:51 UTC, jwp9633 reviewed
고생하셨습니다.