client-sanghyun: Feat/#101 bootcamp
codestates-seb/seb40_main_027 pull request #131
Opened 2022-11-23 04:26 UTC by headring

- 부트캠프 일정 테이블(BootCamp.tsx + Table.tsx)
- 부트캠프 상세 페에지(BootCampSpecific.tsx + SpecificTable.tsx)
- router 조건부 만들기(헤더, 푸터, 접근권한)(PrivateRoute.tsx)
- PageNotFound 생성(PageNotFound.tsx)

2022-11-23 08:54 UTC, jwp9633 requested changes

2022-11-23 08:54 UTC, jwp9633 commented on client/src/components/Table/Table.style.ts
> +      } */
구현 안 할 예정이라면 주석 삭제 부탁드립니다.

2022-11-23 08:54 UTC, jwp9633 commented on client/src/pages/PageNotFound.tsx
> +          <S.HomeLink href="/">Go to Home</S.HomeLink>
한글로 설명하는 건 어떨까요? 한글 웹사이트인데 갑자기 영어로 나오니까 조금 어색하네요.

2022-11-23 08:55 UTC, jwp9633 requested changes

2022-11-23 08:55 UTC, jwp9633 commented on client/src/atoms/index.tsx
> +export const isLogin = atom({
변수명을 소문자로 시작하는 것으로 통일하면 좋을 것 같습니다.

2022-11-23 10:50 UTC, headring commented on client/src/App.tsx
> +        <Route path="/bootcamp/1" element={<BootCampSpecific />} />
일단 페이지를 보는 것이 목적이라서 `:id`라고 기재하지 않았습니다. 
나중에 부트캠프 일정 서버 연동 때 한번에 바꾸려고 합니다.

상세 페이지는 Detail로 통일할게요

2022-11-23 10:56 UTC, headring commented on client/src/components/Header/PageHeader.tsx
> +  justify-content: center; //space betweem
넵 수정했습니다

2022-11-23 11:01 UTC, headring commented on client/src/App.tsx
> +      {location.pathname === '/users/login' || location.pathname === '/users/signup' ? null : location.pathname ===
변수로 선언하면 어떤 것이 더 좋은 지 알수 있을까요?

2022-11-23 11:01 UTC, headring commented on client/src/App.tsx
> +      {location.pathname === '/users/login' || location.pathname === '/users/signup' ? null : <Footer />}
변수로 선언하면 어떤 것이 더 좋은 지 알수 있을까요?

2022-11-23 11:06 UTC, headring commented on client/src/styles/GlobalStyle.tsx
> +    --greenTableHeader: #A9DBBD;
figma에 디자인된 새로운 초록색 색상이 달라서 추가를 했습니다.
같은 초록색이지만 어떤 것은 파스텔톤이며 어떤 것은 채도가 높습니다. 
기존 색을 적용했을 때 조금 어색해서 현재 디자인된 색을 그대로 사용 했습니다.

COLOR.ts에 새로 추가한 색상 추가했습니다.

2022-11-23 11:17 UTC, headring commented on client/src/styles/GlobalStyle.tsx
> +    --grayBootButton: #D9D9D9;
추가했습니다

2022-11-23 11:20 UTC, headring commented on client/src/components/Table/Table.style.ts
> +      } */
삭제했습니다

2022-11-23 11:21 UTC, headring commented on client/src/pages/PageNotFound.tsx
> +          <S.HomeLink href="/">Go to Home</S.HomeLink>
아하 넵 알겠습니다. 코드샌드박스의 것을 거의 그대로 갔고 왔는데 약간 어색할 수 있군요.

2022-11-23 11:55 UTC, headring commented on client/src/pages/PageNotFound.style.ts
> +export const CardLayout = styled.div`
말씀하신대로 수정했습니다. 확인부탁드립니다

2022-11-23 11:56 UTC, headring commented on client/src/pages/BootCamp.tsx
> +    <>
삭제했습니다

2022-11-23 15:29 UTC, headring commented on client/src/pages/BootCampSpecific.tsx
> +          </S.grayBtn>
button 분리시켰습니다

2022-11-23 16:15 UTC, skyhanull commented on client/src/components/Table/DetailTable.style.ts
> +  height: calc(100vh - 20vh);
여기 height부분은 80vh로 적어도 되지 않을까요? calc을 제가 안써봐서 여쭤봅니다

2022-11-24 01:08 UTC, jwp9633 requested changes

2022-11-24 01:08 UTC, jwp9633 commented on client/src/pages/PageNotFound.tsx
> +          <S.HomeLink href="/">메인 페이지 바로가기</S.HomeLink>
HomeLink가 현재 a 요소로 작성되었는데 Link 컴포넌트로 작성하는 게 더 좋을 것 같습니다.

Link 컴포넌트는 client side routing이 기본값이어서 더 이점이 있는 것 같습니다.

2022-11-24 01:08 UTC, jwp9633 commented on client/src/pages/PageNotFound.tsx
> +          <S.HomeLink href="/">Go to Home</S.HomeLink>
저는 좋습니다.

2022-11-24 01:09 UTC, jwp9633 commented on client/src/styles/GlobalStyle.tsx
> +    --greenTableHeader: #A9DBBD;
네 알겠습니다.

2022-11-24 01:09 UTC, jwp9633 commented on client/src/App.tsx
> +        <Route path="/bootcamp/1" element={<BootCampSpecific />} />
네 알겠습니다.

2022-11-24 02:44 UTC, headring commented on client/src/assets/constant/COLOR.ts
> +export const GREEN_TABLE_HEADER = '#A9DBBD';
넵 삭제핬습니다

2022-11-24 02:44 UTC, headring commented on client/src/assets/constant/COLOR.ts
> +export const RED_BOOT_DETAIL_HEART = '#f24e1e';
대문자 변경했습니다

2022-11-24 02:44 UTC, headring commented on client/src/pages/PageNotFound.tsx
> +          <S.HomeLink href="/">메인 페이지 바로가기</S.HomeLink>
Link로 변경했습니다

2022-11-24 02:45 UTC, headring commented on client/src/App.tsx
> +  const location = useLocation().pathname;
구조분해할당 적용했습니다

2022-11-24 02:45 UTC, headring commented on client/src/components/Table/DetailTable.style.ts
> +  height: calc(100vh - 20vh);
calc 함수 지웠습니다

2022-11-24 02:46 UTC, headring commented on client/src/styles/GlobalStyle.tsx
> +    --grayBootButton: #D9D9D9;
재수정하면서 색의 순서 COLOR.ts와 맞췄습니다

2022-11-24 02:50 UTC, headring commented on client/src/components/Table/Table.style.ts
> +      } */
삭제했는데 여기에 반영이 안 되어있네요

2022-11-24 03:00 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-24 05:43 UTC, merged