client -yoonkyoung :my profile구현
codestates-seb/seb40_main_027 pull request #156
Opened 2022-11-25 04:54 UTC by skyhanull

2022-11-27 03:47 UTC, headring requested changes
아래 댓글 확인 부탁드립니다.

2022-11-27 03:47 UTC, headring commented on client/src/components/Header/PageHeader.tsx
> +    width: 1160px;
현재 주석을 살려놓은 이유가 있을까요?

2022-11-27 03:47 UTC, headring commented on client/src/pages/MyPage.tsx
>  const MyPage = () => {
현재 해당 페이지에 들어가면 아래와 같은 경고를 브라우저 콘솔창에서 볼 수 있습니다. 한번 확인 부탁드릴게요.
![스크린샷 2022-11-27 오후 12 25 04](https://user-images.githubusercontent.com/48895268/204117928-ad66cbe8-8dc2-4139-af57-58b4e1a2be31.png)

2022-11-27 03:47 UTC, headring commented on client/src/components/MyPageContent/UserProfile.style.ts
> +export const FormInputProFile = styled.form`
`FromInputProfile`로 변경되는 것 이 더 좋아보입니다

2022-11-27 03:47 UTC, headring commented on client/src/components/MyPageContent/UserProfile.tsx
> +  const MyProfileSubmit: SubmitHandler<IFormInput> = (data: any) => {
받는 데이터가 현제 `any`인데 나중에 다시 작업하실 때 변경 부탁드릴게요

2022-11-27 03:47 UTC, headring commented on client/src/components/SideBar/SideBar.tsx
>          </S.SideBarPage>
반응형으로 갔을 때 햄버거 버튼을 누르면 옆에 사이드바가 안 나오는데 한 번 확인 부탁드릴게요

2022-11-27 07:23 UTC, skyhanull commented on client/src/components/Calculate.tsx
> +  const diff = end - start; // 경과 시간
타입 수정했습니다

2022-11-27 07:23 UTC, skyhanull commented on client/src/components/Calculate.tsx
> +export const calculateTime = (date: any) => {
수정했습니다

2022-11-27 07:32 UTC, skyhanull commented on client/src/pages/MyPage.tsx
>  const MyPage = () => {
링크부분 수정했습니다

2022-11-27 07:32 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.style.ts
> +export const FormInputProFile = styled.form`
이름 변경했습니다

2022-11-27 07:34 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +  const MyProfileSubmit: SubmitHandler<IFormInput> = (data: any) => {
이부분에서 궁금한게 있는데 제가 data의 타입으로 InformInput을 앞의 submithandler와 같게 뒀는데 뒤에 data의 타입과 같으면 앞에  SubmitHandler<IFormInput>은 지우는게 맞을까요?

2022-11-27 07:34 UTC, skyhanull commented on client/src/components/SideBar/SideBar.tsx
>          </S.SideBarPage>
수정했습니다

2022-11-27 07:55 UTC, skyhanull commented on client/src/components/Header/PageHeader.tsx
> +    width: 1160px;
pull할때 병합이 되서 어느부분을 삭제할지 애매해 우선 살려놓았습니다

2022-11-29 01:14 UTC, jwp9633 requested changes

2022-11-29 01:14 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageLists.style.ts
> +import styled from 'styled-components';
ForumAritcle.tsx 내용을 복사해서 사용하기 보다 직접 컴포넌트를 활용하면 어떨까요?

2022-11-29 01:14 UTC, jwp9633 commented on client/src/components/MyPageContent/UserProfile.tsx
> +          'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJzdWIiOiJsYWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ4MTI0OSwiZXhwIjoxNjY5NTI0NDQ5fQ.Fwfii5XFjTe_6W9Zm20h8rDG0
인증 관련 토큰을 github에 올리는 것은 위험합니다.

2022-11-29 01:14 UTC, jwp9633 commented on client/src/components/MyPageContent/UserProfile.tsx
> +        let datatype = res.data;
`const dataType`으로 작성하면 어떨까요?

2022-11-29 01:14 UTC, jwp9633 commented on client/src/components/Withdrawal.tsx
> +            'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoiaGVoZUBnbWFpbC5jb20iLCJzdWIiOiJoZWhlQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ0NTA1NiwiZXhwIjoxNjY5NDg4MjU2fQ.xW0VydYPypKjjvOmEdLQjuI
토큰 삭제 부탁드려요.

2022-11-29 01:14 UTC, jwp9633 commented on client/src/pages/MyPage.style.ts
> +  overflow-y: auto; // 나중에 재수정할 수 도 있을 것 같아서 일단 주석 처리만 진행햇어요.
수정 완료 되었다면 주석을 삭제하는 게 어떨까요?

2022-11-29 01:39 UTC, skyhanull commented on client/src/components/Withdrawal.tsx
> +            'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoiaGVoZUBnbWFpbC5jb20iLCJzdWIiOiJoZWhlQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ0NTA1NiwiZXhwIjoxNjY5NDg4MjU2fQ.xW0VydYPypKjjvOmEdLQjuI
이부분은 나중에 상현님이 로그인쪽 완성해주시면 local에서 가져오는 형식으로 바꿀예정인데 우선 올릴때는 지우는 편이 좋을까요?

2022-11-29 01:39 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +          'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJzdWIiOiJsYWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ4MTI0OSwiZXhwIjoxNjY5NTI0NDQ5fQ.Fwfii5XFjTe_6W9Zm20h8rDG0
이부분은 나중에 상현님이 로그인쪽 완성해주시면 local에서 가져오는 형식으로 바꿀예정인데 우선 올릴때는 지우는 편이 좋을까요?

2022-11-29 01:40 UTC, headring commented on client/src/components/MyPageContent/UserProfile.tsx
> +  const MyProfileSubmit: SubmitHandler<IFormInput> = (data: any) => {
<img width="802" alt="스크린샷 2022-11-29 오전 10 40 18" src="https://user-images.githubusercontent.com/48895268/204417387-48e7d854-cb56-4821-a1e0-9720d81e8d63.png">
저는 위 사진과 같이 작성했습니다. data뒤에 any는 지워도 될 것 같아요

2022-11-29 02:12 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageLists.tsx
> +import { ko } from 'date-fns/locale';
date-fns다시 설치했습니다

2022-11-29 02:12 UTC, skyhanull commented on client/src/App.tsx
>  import PageHeader from './components/Header/PageHeader';
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/Header/Nickname.tsx
> +        <span className="user-img">사</span>
말씀하신 아이콘으로 수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/Header/PageHeader.tsx
> +`;
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/Header/PageHeaderSide.tsx
> +        </div>
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/Logout/Logout.tsx
> +            'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJzdWIiOiJsYWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ4MTI0OSwiZXhwIjoxNjY5NTI0NDQ5fQ.Fwfii5XFjTe_6W9Zm20h8rD
이부분은 나중에 상현님이 로그인쪽 완성해주시면 토큰을 local에서 가져오는 형식으로 바꿀예정인데 우선 올릴때는 지우는 편이 좋을까요?

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/Logout/Logout.tsx
> +    </div>
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageList.tsx
>    .mycontent-info {
이부분은 쓰이는 부분이 아니라 삭제했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +        let datatype = res.data;
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/pages/MyPage.style.ts
> +  overflow-y: auto; // 나중에 재수정할 수 도 있을 것 같아서 일단 주석 처리만 진행햇어요.
수정했습니다

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageLists.style.ts
> +import styled from 'styled-components';
죄송하지만 이부분이 잘 이해가 안가서 질문드립니다 제생각에는 글을 불러오는 것이라 모양이 같아야 할 것 같아 가져온 것인데 직접 컴포넌트 화 하라는 말씀은 어떤 뜻일까요?

2022-11-29 02:20 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +  const MyProfileSubmit: SubmitHandler<IFormInput> = (data: any) => {
뒤에 data부분 안에 타입을 삭제했습니다

2022-11-29 02:20 UTC, headring approved these changes
아래 한번만 확인 부탁드립니다

2022-11-29 02:20 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +          {columns.map((item, idx) => {
idx값이 사용 안 되는데 삭제해도 될 것 같아요

2022-11-29 02:24 UTC, headring commented on client/src/components/MyPageContent/MyPageList.tsx
> +    // updatedAt: '2022-11-20T16:35:41.87709',
이전 git pull했을 때 보여서 코멘트 남긴거라 수정 되었으면 넘어가셔도 됩니다

2022-11-29 02:25 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +          {columns.map((item, idx) => {
이전 git pull했을 때 보여서 코멘트 남긴거라 수정 되었으면 넘어가셔도 됩니다

2022-11-29 02:29 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageLists.style.ts
> +import styled from 'styled-components';
이미 만든 컴포넌트인 ForumArticle을 import 해서 사용하면 어떨까 말씀드린거에요.

2022-11-29 02:30 UTC, jwp9633 commented on client/src/components/MyPageContent/UserProfile.tsx
> +          'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJzdWIiOiJsYWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ4MTI0OSwiZXhwIjoxNjY5NTI0NDQ5fQ.Fwfii5XFjTe_6W9Zm20h8rDG0
네 보안에 민감한 정보는 지우는 게 좋습니다.

2022-11-29 02:31 UTC, jwp9633 commented on client/src/components/MyPageContent/UserProfile.tsx
> +        let datatype = res.data;
camelCase로 수정 부탁드려요.

2022-11-29 02:31 UTC, jwp9633 commented on client/src/components/MyPageContent/UserProfile.tsx
> +        const datatype = res.data;
camelCase로 수정 부탁드립니다.

2022-11-29 02:31 UTC, jwp9633 commented on client/src/components/Withdrawal.tsx
> +            'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoiaGVoZUBnbWFpbC5jb20iLCJzdWIiOiJoZWhlQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ0NTA1NiwiZXhwIjoxNjY5NDg4MjU2fQ.xW0VydYPypKjjvOmEdLQjuI
네 보안에 민감한 정보는 지우는 게 좋습니다.

2022-11-29 02:35 UTC, jwp9633 requested changes

2022-11-29 02:35 UTC, jwp9633 commented on client/src/components/Button/Logout.tsx
> +    </>
지금보니 <></>으로 감쌀 필요가 없네요.

2022-11-29 02:50 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageLists.style.ts
> +import styled from 'styled-components';
두 style파일을 비교해봤는데 비슷한 것이 많으나 완전 같은것은 한두개 밖에 안되서 굳이 import를 하지 않아도 될 것 같습니다

2022-11-29 02:52 UTC, skyhanull commented on client/src/components/Button/Logout.tsx
> +    </>
수정했습니다

2022-11-29 02:52 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +        const datatype = res.data;
수정했습니다

2022-11-29 02:52 UTC, skyhanull commented on client/src/components/Withdrawal.tsx
> +            'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoiaGVoZUBnbWFpbC5jb20iLCJzdWIiOiJoZWhlQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ0NTA1NiwiZXhwIjoxNjY5NDg4MjU2fQ.xW0VydYPypKjjvOmEdLQjuI
수정했습니다

2022-11-29 02:52 UTC, skyhanull commented on client/src/components/MyPageContent/UserProfile.tsx
> +          'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJzdWIiOiJsYWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQ4MTI0OSwiZXhwIjoxNjY5NTI0NDQ5fQ.Fwfii5XFjTe_6W9Zm20h8rDG0
수정했습니다

2022-11-29 04:26 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageLists.style.ts
> +import styled from 'styled-components';
모양과 내용이 같다면 ForumArticle 컴포넌트를 재사용하는 것이 맞다고 생각합니다

2022-11-29 04:51 UTC, jwp9633 approved these changes
컴포넌트 재사용은 추후에 다시 봐야 할 것 같습니다.

2022-11-29 04:54 UTC, merged