client-yoonkyoung : Feat/#7 header,logo
codestates-seb/seb40_main_027 pull request #17
Opened 2022-11-14 05:43 UTC by skyhanull

2022-11-14 08:26 UTC, headring commented
확인했습니다

2022-11-14 08:46 UTC, jwp9633 requested changes
코멘트 보시고 이해가 안 되거나 다른 의견이 있으면 언제든 말씀해주세요. 작업하시느라 고생하셨습니다.

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/Mainheader.tsx
> +  @media screen and (max-width: 414px) and (max-height: 667px) {
저희 가로 길이에 따라서만 반응형으로 제작하기로 해서 max-heigt 항목은 필요 없을 것 같습니다.

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/Mainheader.tsx
> +  border-bottom: 1px solid #d6d6d6;
#d6d6d6 대신 글로벌 스타일에 선언한 변수를 사용하면 어떨까요?

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/Nickname.tsx
> +const Imgcircle = styled.span`
Pascal Case로 수정하는 게 좋을 것 같습니다.

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/Nickname.tsx
> +  .userimg {
저희 이번에 클래스 네이밍 규칙으로 정한 user-img로 수정하면 좋을 것 같습니다.

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/PageHeader.tsx
> +  border-bottom: 1px solid #d6d6d6;
#d6d6d6 대신 글로벌 스타일에 선언한 변수를 사용하면 어떨까요?

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/PageHeader.tsx
> +  .pagemenu {
저희 이번에 정한 클래스 네이밍 규칙으로 수정하면 좋을 것 같습니다.

2022-11-14 08:46 UTC, jwp9633 commented on client/src/components/PageHeader.tsx
> +  @media screen and (max-width: 414px) and (max-height: 667px) {
저희 가로 길이에 따라서만 반응형으로 제작하기로 해서 max-heigt 항목은 필요 없을 것 같습니다.

2022-11-14 08:53 UTC, headring commented on client/src/components/Mainheader.tsx
> +const HeaderContent = styled.div`
아까 말씀드렸다시피 semantic tag위에 다시 div가 덮여져 있어서 해당 div를 semantic tag인 header로 변경하고 다시 수정하는 것이 더 좋을 듯 합니다. 혹시 해당 작업이 까다로우면 같이 해결해봐도 되니 편히 말씀 부탁드릴게요 :)

2022-11-15 00:26 UTC, jwp9633 requested changes

2022-11-15 00:26 UTC, jwp9633 commented on client/src/components/Header/PageHeader.tsx
> +  const headermenu = ['분야선택', '로드맵', '학원일정', '수료후기', '스터디모집', '멘토링'];
camelCase로 작성하는 것이 좋을 것 같습니다.

2022-11-15 01:46 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-15 01:47 UTC, merged