client-sanghyun: Feat/#11 footer
codestates-seb/seb40_main_027 pull request #19
Opened 2022-11-14 06:29 UTC by headring

footer 기초 틀 완료
- 반응형 및 데스크탑 css 적용
- 일부 a tag 링크에 필요한 링크로 이동

2022-11-14 08:55 UTC, jwp9633 requested changes
고생하셨습니다. 코멘트에 대한 다른 의견이나 질문 있으면 언제든 말씀해주세요.

2022-11-14 08:55 UTC, jwp9633 commented on client/src/components/Footer/Footer.tsx
> +  .footer_inner {
저희가 정한 클래스 네이밍 규칙으로 수정하면 좋을 것 같습니다.

2022-11-14 08:55 UTC, jwp9633 commented on client/src/components/Footer/Footer.tsx
> +    }
중괄호 내부에 설정된 스타일이 없어서 지우는 게 좋을 것 같습니다.

2022-11-14 08:55 UTC, jwp9633 commented on client/src/components/Footer/Footer.tsx
> +            idx < 2 ? (
위에는 `idx <= 1`, 아래는 `idx >= 2`로 작성하면 가독성이 더 좋을 것 같습니다.

2022-11-14 08:55 UTC, jwp9633 commented on client/src/components/Footer/Footer.tsx
> +        <div className="inner_rigth">
오타 있습니다. rigth  -> right
그리고 클래스를 사용하지 않는 것 같아서 className을 지우는 건 어떨까요?

2022-11-14 12:59 UTC, skyhanull commented on client/src/components/Footer/Footer.tsx
> +        <div className="inner_rigth">
확인했습니다

2022-11-14 12:59 UTC, skyhanull commented
확인했습니다

2022-11-15 00:07 UTC, jwp9633 requested changes

2022-11-15 00:07 UTC, jwp9633 commented on client/src/components/Footer/Footer.tsx
> +  .footer_inner {
.footer_inner -> .footer-inner로 수정되어야 할 것 같습니다.

2022-11-15 00:26 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-15 01:41 UTC, merged