client-sanghyun: Feat/#132 user api
codestates-seb/seb40_main_027 pull request #190
Opened 2022-11-29 05:41 UTC by headring

로그인 시 이용
- 전역상테(atom):
```js
  default: {
    isLog: false,
    member_role: '',
    nickname: '',
  },
```
- 토큰 저장 위치: localstorage
  - 변수이름 `access` 
  - 변수이름 `refresh` 

[merge이후 작업 예정]
*다른 branch에서 접근권한 인가 후 redirection 작업 예정
*윤경님 hook파일 위치와 api파일 위치 조정

2022-11-29 06:06 UTC, skyhanull commented
<img width="982" alt="스크린샷 2022-11-29 오후 3 04 38" src="https://user-images.githubusercontent.com/106054006/204451715-cef34628-846b-4f8d-8ec9-895ee0700528.png">
recoil-persist 오류가 발생합니다

2022-11-29 06:30 UTC, skyhanull commented
<img width="500" alt="스크린샷 2022-11-29 오후 3 16 31" src="https://user-images.githubusercontent.com/106054006/204455434-80c2c639-9008-464e-b893-8b41f11d5c9c.png">
로그인 성공시 옆에 [object Objext]가 나오는데 다른 것으로 수정해주시면 좋을 것 같습니다

2022-11-29 06:31 UTC, skyhanull commented on client/src/pages/Login.tsx
> +};
type과 interface 둘 다 비슷한 건 알지만 하나로 통일해도 좋지않을까요?

2022-11-29 06:31 UTC, skyhanull commented on client/src/pages/Login.tsx
> +            <Link to="/users/signup">회원가입</Link>
회원가입 밑에 text-decoration이 있는데 none으로 해주면 좋을 것 같습니다

2022-11-30 04:17 UTC, jwp9633 requested changes

2022-11-30 04:17 UTC, jwp9633 commented on client/src/pages/Login.tsx
> +            />
className indicator는 사용하지 않는 것 같습니다.

아래처럼 수정하면 어떨까요?
label 요소에 htmlFor 속성으로 input 요소의 id 속성과 연결하는 방식입니다.
이 방식이 일반적으로 권장되는 것으로 알고 있습니다.
```tsx
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="text"
              {...register('email', {
                required: '아이디를 입력해주세요',
                pattern: {
                  value: /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i,
                  message: '이메일 형식으로 입력해주세요',
                },
              })}
              placeholder="이메일을 입력하세요"
            />
```

2022-11-30 04:17 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +              </label>
여기서의 label 요소도 Login.tsx에서 제가 말씀 드린 것처럼 작성하면 어떨까요?

2022-11-30 04:17 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +                      value: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,20}$/,
정규식에서는 설명과 다르게 글자수 제한이 8-20자입니다.

2022-11-30 04:17 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +  password.current = watch('password', '');
useRef를 사용하신 이유가 있으실까요?

아래처럼 작성해도 될 것 같습니다.
```tsx
const watchPassword = watch('password', '');
```
https://react-hook-form.com/api/useform/watch

2022-11-30 04:17 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +              ) : null} */}
주석을 남겨두신 이유가 있을까요?

2022-11-30 04:18 UTC, jwp9633 commented
리뷰 반영하시면서 로컬에서 client 브랜치를 pull 하여 conflict도 해결 부탁드립니다.

2022-11-30 04:47 UTC, headring commented on client/src/pages/Login.tsx
> +};
interface로 통합했습니다

> <img alt="스크린샷 2022-11-29 오후 3 16 31" width="500" src="https://user-images.githubusercontent.com/106054006/204455434-80c2c639-9008-464e-b893-8b41f11d5c9c.png">
> 
> 로그인 성공시 옆에 [object Objext]가 나오는데 다른 것으로 수정해주시면 좋을 것 같습니다

회원가입 시 나오는 alert라서 글자 변경하고 response 삭제했습니다

2022-11-30 04:48 UTC, headring commented on client/src/pages/Login.tsx
> +            <Link to="/users/signup">회원가입</Link>
적용했습니다

2022-11-30 04:48 UTC, headring commented on client/src/hooks/useUsers.tsx
> +import { RecoilState } from 'recoil';
삭제했습니다

2022-11-30 04:48 UTC, headring commented on client/src/hooks/useUsers.tsx
> +      alert(`로그인 성공 ${response}`);
회원가입 시 나오는 alert라서 글자 변경하고 response 삭제했습니다

2022-11-30 04:49 UTC, headring commented on client/src/hooks/useUsers.tsx
> +  member_role: string;
응답필드명과 같이 한 거라서 수정 가능합니다. `memberRole`로 변경해놓을게요

2022-11-30 04:57 UTC, headring commented on client/src/hooks/useUsers.tsx
> +interface LogInType {
interface LoginType으로 변경했습니다

2022-11-30 04:58 UTC, headring commented on client/src/hooks/useUsers.tsx
> +export const useLogIn = (
useLogin으로 수정하고 import문들도 수정했습니다

2022-11-30 05:01 UTC, headring commented on client/src/pages/SignUp.tsx
> +                      value: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,20}$/,
로그인 및 회원가입 정규표현식에 전부 최소 4개로 수정했습니다

2022-11-30 05:04 UTC, headring commented on client/src/pages/SignUp.tsx
> +  password.current = watch('password', '');
올려주신 코드로 변경했습니다

2022-11-30 05:04 UTC, headring commented on client/src/pages/SignUp.tsx
> +              ) : null} */}
에러메세지 확인하느라 남겨뒀던 건데 지웠습니다

2022-11-30 05:12 UTC, headring commented on client/src/pages/SignUp.tsx
> +              </label>
label 안에서 모든 요소를 작성하는 [방법](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md)이 가장 위에 있어서 이렇게 적었습니다. 다만 해당 경고를 로그인 시 반영을 못해서 현재 스타일을 로그인에 반영시킬게요.

2022-11-30 05:20 UTC, headring commented on client/src/pages/Login.tsx
> +            />
말씀하신 부분 맞지만 변경 시 스타일 변경이 따라와서 아래와 같이 통일시켰습니다.

2022-11-30 05:30 UTC, headring commented on client/src/hooks/useUsers.tsx
> +interface LogInType {
지금보니 회원가입은 SignUp이라서 Login을 LogIn으로 전부 수정할게요

2022-11-30 05:31 UTC, headring commented on client/src/hooks/useUsers.tsx
> +};
customHook에서 제거하고 utils/api 안에 usersAPI.ts로 변경하고 useLogin 및 useSignup을 전부 userLogIn 및 userSignUp으로 변경했습니다

2022-11-30 05:31 UTC, headring commented on client/src/hooks/useUsers.tsx
> +};
위 답변과 같습니다

2022-11-30 07:24 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-30 07:24 UTC, jwp9633 commented on client/src/utils/api/userAPI.ts
> +      const refresh = response.headers.refresh || '';
|| 연산자 보다 ?? 연산자 사용이 더 좋을 것 같습니다.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2022-11-30 07:27 UTC, jwp9633 commented on client/src/utils/api/userAPI.ts
> +    })
response를 사용하지 않으므로 인자로 받아오지 않아도 될 것 같습니다.

2022-11-30 08:43 UTC, headring commented on client/src/utils/api/userAPI.ts
> +      const refresh = response.headers.refresh || '';
넵 확인했습니다

2022-11-30 08:43 UTC, headring commented on client/src/utils/api/userAPI.ts
> +    })
넵 수정했습니다

2022-11-30 08:45 UTC, merged