client-yoonkyoung: comment
codestates-seb/seb40_main_027 pull request #226
Opened 2022-12-01 08:27 UTC by skyhanull

이 브랜치에서는 제가 따로 브랜치를 파는 걸 까먹고 답글부분하고 페이지네이션부분이 구현되었습니다 +로드맵 css추가
1.댓글부분 => 생성/수정부분 고쳐진 부분이 아직 배포되지 않아 배포되면 다시 수정할 예정입니다 //주석처리된부분 남은이유(createtime)
1-1. api파일에 get,delete는 data{}가 없어서 따로 컴포넌트화가 가능했으나 나머지는 data때문에 오류가 나와서 따로 빼서 만들지 않았습니다
2.페이지네이션을 구현을 했으나 크기에 따라 한페이지의 크기가 달라져 우선 10개로 두고 스크롤로 내릴수 있게 조정을 했습니다
3.페이지네이션부분 코드를 제가 작성을 하긴했는데 이부분 너무 넘기는 props가 많아서 시간이 된다면 고쳐볼 부분입니다 =>의견환영
4.마이페이지 찜한일정은 고치긴했으나 틀만 잡은거라 다시 브랜치를 파서 구현할 예정입니다->수정을하면 다른 브랜치에서 수정을 할 듯합니다

2022-12-01 13:54 UTC, jwp9633 requested changes

2022-12-01 13:54 UTC, jwp9633 commented on client/src/utils/API/getApi.tsx
> +  });
에러 처리가 안 되어 있습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/ForumAnswer.style.ts
> +export const SubmitButtton = styled(StyledBackgroundButton)`
오타 수정해주세요.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/ForumAnswer.style.ts
> +    overflow-y: scroll;
현재 작성된 댓글이 넘쳤을 때 댓글들만 스크롤 되고, 댓글 작성칸은 밑에 고정되어 있습니다.

댓글 작성칸까지 같이 스크롤되면 좋을 것 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +      console.log('err');
에러 처리를 더 개선하면 좋을 것 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +    axios.defaults.withCredentials = true;
withCredentials 옵션을 넣은 이유가 있으실까요?

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +        <S.QuillArea theme="snow" value={answerContents} onChange={(e) => setAnswerContents(e)} />
`(e) => setAnswerContents(e)` -> `setAnswerContents` 으로 작성하면 어떨까요?

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +      console.log('err');
위와 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +    axios.defaults.withCredentials = true;
위와 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +        <S.QuillArea theme="snow" value={mentoringAnswerContents} onChange={(e) => setMentoringnAnswerContents(e)} />
위와 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswerList.tsx
> +import axios from 'axios';
위 파일과 내용이 같아서 리뷰는 안 남기겠습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/StudyAnswer.tsx
> +import { useState, useEffect } from 'react';
위 파일과 내용이 같아서 리뷰 안 남기겠습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Answer/StudyAnswerList.tsx
> +import axios from 'axios';
위와 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/Header/Nickname.tsx
> +        <Link to={'users/mypage'}>
to={'users/mypage'} -> to="users/mypage" 이렇게 작성하면 더 좋을 것 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +          'Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImVtYWlsIjoiYWJjZEBnbWFpbC5jb20iLCJzdWIiOiJhYmNkQGdtYWlsLmNvbSIsImlhdCI6MTY2OTc5Mzk4OSwiZXhwIjoxNjY5ODgwMzg5fQ.jwHPEroDLyZmiL2TRvYuvaED2
토큰 삭제해주세요.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +    axios.defaults.withCredentials = true;
withCredentials 옵션은 필요 없을 것 같습니다.

2022-12-01 13:54 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +      // const Maxarr = [...data.data.studies, ...sWritingList, ...mWritingList];
주석 남겨두신 이유가 있으실까요?

2022-12-02 01:48 UTC, headring approved these changes
아래 한번만 확인해주시면 됩니다

2022-12-02 01:48 UTC, headring commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +  const AsyncFunction = async () => {
async을 이용한 함수 대부분 camelCase로 작성했는데 혹시 이 부분은 PascalCase로 작성하신 이유가 있을까요?
(현재 AsyncFunction 변수들은 전부 PascalCase입니다)

2022-12-02 01:48 UTC, headring commented on client/src/components/Answer/MentoringAnswer.tsx
> +export interface mentoringAnswerList extends Array<mentoringAnswerListProps> {}
보통 타입은 PascalCase로 작성을 하기에 이 부분 PascalCase로 작성하는 것도 좋을 듯합니다.
바로 위의 interface도 같습니다

2022-12-02 01:48 UTC, headring commented on client/src/components/Forum/ForumDetail.tsx
> +            {/* {post[`${forumType}Comments`].map((comment: any) => (
주석을 살려놓은 이유가 있을까요?

2022-12-02 01:48 UTC, headring commented on client/src/pages/LoadMap.tsx
> +          <SelectButton
버튼 클릭 시 아래와 같이 유지가 됩니다. 유지되는 것보다 hover만 해주고 끝내는 방향은 어떨까요?
재클릭 시 페이지로 이동이 안 됩니다.
![스크린샷 2022-12-02 오전 10 47 48](https://user-images.githubusercontent.com/48895268/205196208-5aa61bdc-9fc7-41c2-979c-8ffe40d36db1.png)

2022-12-02 01:50 UTC, headring commented
추가적으로 PageHeader부분에서 로드맵을 눌렀을 때 이동이 없는 데 링크 연결해주실 수 있을까요?

2022-12-02 01:51 UTC, headring commented
댓글 작성 후 바로 렌더링 될 때 아래와 같이 `1분 미만 후`라고 나오는데 확인이 가능할까요?
![스크린샷 2022-12-02 오전 10 27 10](https://user-images.githubusercontent.com/48895268/205196614-66954da3-7440-48f2-a5de-2e92f06ee480.png)

2022-12-02 02:48 UTC, skyhanull commented on client/src/pages/LoadMap.tsx
> +          <SelectButton
이부분 우선 크기는 같게했으나 hover를 안쓴이유가 모바일에서는 호버가 작동을 안해서 클릭시 버튼색이 바뀌게 했습니다 그리고 링크는 버튼자체가 아니고 글자를 눌렀을 때만 이동하게 만들어서 글자를 누르셔도 이동이 안되는지 궁금합니다

2022-12-02 02:48 UTC, skyhanull commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +  const AsyncFunction = async () => {
수정했습니다

2022-12-02 02:48 UTC, skyhanull commented on client/src/components/Answer/MentoringAnswer.tsx
> +export interface mentoringAnswerList extends Array<mentoringAnswerListProps> {}
이부분은 위에 종원님의 리뷰랑 달라서 이야기가 필요할 것 같습니다

2022-12-02 02:59 UTC, jwp9633 requested changes

2022-12-02 02:59 UTC, jwp9633 commented on client/src/atoms/index.tsx
> +import { mentoringAnswerList } from '../components/Answer/MentoringAnswer';
이 부분은 제가 말씀을 잘못드렸습니다. 죄송합니다.

타입이기 때문에 PascalCase로 작성하는 것이 더 좋을 것 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/AnswerListView.style.ts
> +  &:last-child(1) {
`&:last-child(1)` -> `&:last-child`으로 수정 부탁드립니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/AnswerListView.style.ts
> +  span:nth-last-child(1) {
26번째 줄은 수정 안된 것 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/AnswerListView.tsx
> +  const PatchHanlder = (e: React.MouseEvent<HTMLElement>) => {
PatchHanlder 오타 수정해주세요.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/AnswerContainer.tsx
> +  const updateTime = formatDistanceToNow(new Date(updateAt), { addSuffix: true, locale: ko });
nick -> nickname, updateAt -> updatedAt, createAt -> createdAt 으로 수정하면 좋을 것 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +export interface iAnswerList extends Array<answerListProps> {}
타입은 PascalCase로 작성 부탁드립니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +            key={idx}
answerList에는 commentId가 있기 때문에 이를 key로 활용하는 것이 더 적절할 것 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +  const [mentoringanswerList, setMentoringAnswerList] = useRecoilState(mentoringListData);
camelCase로 작성 부탁드리겠습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +            key={idx}
위와 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswerList.tsx
> +  const PatchHanlder = (e: React.MouseEvent<HTMLElement>) => {
오타 수정해주세요.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/StudyAnswer.tsx
> +  const [studyanswerList, setStudyAnswerList] = useRecoilState(studyListData);
23번째 줄 오타 수정해주세요.
24번째 줄 camelCase로 작성해주세요.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/StudyAnswer.tsx
> +            key={idx}
위와 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/Answer/StudyAnswerList.tsx
> +  const PatchHanlder = (e: React.MouseEvent<HTMLElement>) => {
오타 수정해주세요.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +      const Maxarr: propsAnswerList = [...postP, ...postS, ...postM].sort(
camelCase로 작성해주세요.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +  const [emailPost, setEmailPost] = useState('');
emailPosts를 사용하지 않는데 state로 선언하신 이유가 궁금합니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +      setEmailPost(data.data.nickname);
변수명이 EmailPost인데 nickname을 할당하는 이유가 있으실까요?

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageList.tsx
> +              key={idx}
key 값으로 id를 사용하는 게 더 좋을 것 같습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
> +import { useInView } from 'react-intersection-observer';
useCallback, useInView는 사용하지 않습니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
>  import { Icon } from '@iconify/react';
Icon은 사용하지 않으므로 삭제 부탁드립니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  };
getItem은 사용하지 않는 함수입니다.

2022-12-02 02:59 UTC, jwp9633 commented on client/src/pages/LoadMap.tsx
> +  const Loadmapmenu = [
camelCase로 작성해주세요

2022-12-02 03:03 UTC, skyhanull commented on client/src/components/Answer/AnswerContainer.tsx
> +  const updateTime = formatDistanceToNow(new Date(updateAt), { addSuffix: true, locale: ko });
수정했습니다

2022-12-02 03:04 UTC, skyhanull commented on client/src/components/Answer/ForumArticlesAnswer.tsx
> +            key={idx}
수정했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/atoms/index.tsx
> +import { mentoringAnswerList } from '../components/Answer/MentoringAnswer';
원래대로 수정했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/Answer/AnswerListView.style.ts
> +  &:last-child(1) {
수정햇습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/Answer/AnswerListView.style.ts
> +  span:nth-last-child(1) {
수정 다시 완료했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/Answer/StudyAnswer.tsx
> +            key={idx}
수정했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageList.tsx
> +  const [emailPost, setEmailPost] = useState('');
이부분은 닉네임을 가져오려다가 다른방법을 써서 지우는 걸 까먹었습니다 수정했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageList.tsx
> +      setEmailPost(data.data.nickname);
이부분은 닉네임을 가져오려다가 다른방법을 써서 지우는 걸 까먹었습니다 수정했습니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  };
이함수는 이 브랜치 이후 다른브랜치에서 구현을 할예정인 함수입니다

2022-12-02 03:22 UTC, skyhanull commented on client/src/pages/LoadMap.tsx
> +  const Loadmapmenu = [
수정했습니다

2022-12-02 04:29 UTC, jwp9633 commented on client/src/components/Answer/MentoringAnswer.tsx
> +  const [mentoringanswerList, setMentoringAnswerList] = useRecoilState(mentoringListData);
setMentoringnAnswerContents 오타 수정해주세요.

2022-12-02 04:35 UTC, jwp9633 commented on client/src/pages/LoadMap.tsx
> +  const Loadmapmenu = [
75번째 줄은 PascalCase로 작성되어 있습니다. camelCase로 수정 부탁드립니다.

2022-12-02 04:35 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  };
그러면 현재 브랜치에서는 삭제 또는 주석 처리하는 것이 좋을 것 같습니다.

2022-12-02 04:38 UTC, jwp9633 requested changes

2022-12-02 04:38 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  const [offset, setOffset] = useState(0);
loading, offset, setOffset은 현재 사용하지 않고 있는데, 남겨두신 이유가 있으실까요?

2022-12-02 04:55 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  const [offset, setOffset] = useState(0);
이부분은 원래 무한스크롤을 구현하려고 남겨둔 부분인데 삭제하겠습니다

2022-12-02 05:06 UTC, jwp9633 commented on client/src/utils/API/getApi.tsx
> +  });
아마 타입 선언이 문제인 것 같습니다. 일단은 넘어가셔도 될 것 같아요.

2022-12-02 05:07 UTC, skyhanull commented on client/src/components/MyPageContent/MyPageTable.tsx
> +  };
주석처리했습니다

2022-12-02 05:07 UTC, skyhanull commented on client/src/components/Answer/MentoringAnswer.tsx
> +  const [mentoringanswerList, setMentoringAnswerList] = useRecoilState(mentoringListData);
오타수정했습니다 혹시몰라 확인부탁합니다

2022-12-02 05:11 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-12-02 05:12 UTC, headring commented on client/src/pages/LoadMap.tsx
> +          <SelectButton
아하 글자만 되는 거였네요. 확인했습니다

2022-12-02 05:13 UTC, merged