client-sanghyun: Feat/#175 client bootcamp
codestates-seb/seb40_main_027 pull request #257
Opened 2022-12-03 08:30 UTC by headring

학원일정, 스터디, 멘토링, 마이페이지에 무한 스크롤을 적용했습니다. 

- ForumCars.tsx에 useSearchParams 쓰실 예정인지 확인 부탁드립니다
- mypage왼쪽 userprofile부분 border보다 찜한 일정이 더 많아져서 css 도움이 필요합니다
- 현재 무한스크롤이 되긴하나 첫 화면 렌더링 시 현재 최대 3page를 한 꺼번에 불러오고 있습니다. 혹시 방법이 있으신분은 말씀부탁드릴게요

2022-12-03 14:13 UTC, headring commented on client/src/hooks/useBootTable.tsx
> +import { DataType } from '../components/Table/DetailTable';
넵 삭제했습니다

2022-12-03 14:13 UTC, headring commented on client/src/hooks/useBootTable.tsx
> +        console.log(resopnse.data);
넵 삭제했습니다

2022-12-03 14:15 UTC, headring commented on client/src/components/Forum/ForumCards.tsx
> +  const getPosts = useCallback(async (page: any) => {
타입을 숫자로 변경했습니다

2022-12-03 14:53 UTC, jwp9633 commented
ForumCards.tsx에 useSearchParams 사용 안해도 상관없습니다.

2022-12-03 15:23 UTC, jwp9633 requested changes

2022-12-03 15:23 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
>  import { bootListMyPage } from '../../atoms/index';
4, 9번째 줄은 사용하지 않는 것 같습니다.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/components/MyPageContent/MyPageTable.tsx
> +      console.log('i am', page);
콘솔 로그 삭제 부탁드려요.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/components/Table/Table.style.ts
> +import { ContentWrapper } from './../../pages/Forum.style';
1번째 줄은 사용하지 않는 것 같습니다.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/hooks/useBootTable.tsx
> +      setData(resopnse.data);
response 오타 수정해주세요.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/hooks/useBootTable.tsx
> +        setData(resopnse.data.data);
response 오타 수정해주세요.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/index.tsx
> +  </RecoilRoot>
React.StrictMode는 개발 모드에서 2번 실행을 하기 때문에 저는 필요하다고 생각합니다.

배포 시 1번 실행될 것으로 추측되고 만약 2번 실행된다면 그때 삭제하는 게 더 좋을 것 같습니다.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/pages/BootCamp.tsx
> +    await setLoading(false);
22, 28번째 줄 set 함수는 프로미스가 아니므로 await이 동작하지 않을 것 같습니다.

24번째 줄 콘솔 삭제 부탁드려요.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/pages/BootCampDetail.tsx
> +        setItems(resopnse.data.data);
response 오타 수정 부탁드려요.

2022-12-03 15:23 UTC, jwp9633 commented on client/src/pages/BootCampDetail.tsx
> +          <a href={`${items.site}`} target="_blank" rel="noopener noreferrer">
로컬에서 테스트할 때 홈페이지로 이동이 안되는 것 같습니다. 확인 부탁드려요.

2022-12-03 16:49 UTC, headring commented on client/src/pages/BootCampDetail.tsx
> +          <a href={`${items.site}`} target="_blank" rel="noopener noreferrer">
지금 이거 같은 경우는 데이터베이스 쪽의 사이트 url 형식이 통일화가 안 되어 있는 것 같네요. 이 부분은 백엔드와 논의하겠습니다

2022-12-03 16:49 UTC, headring commented on client/src/pages/BootCampDetail.tsx
> +        setItems(resopnse.data.data);
오타 수정했습니다

2022-12-03 16:49 UTC, headring commented on client/src/index.tsx
> +  </RecoilRoot>
다시 살려놓을게요

2022-12-03 16:49 UTC, headring commented on client/src/hooks/useBootTable.tsx
> +        setData(resopnse.data.data);
오타 수정했습니다

2022-12-03 16:49 UTC, headring commented on client/src/hooks/useBootTable.tsx
> +      setData(resopnse.data);
오타 수정했습니다

2022-12-03 16:49 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +        <S.RefDiv ref={ref}>{inView && loading ? <Loading /> : null}</S.RefDiv>
div 요소를 밖으로 뻈습니다

2022-12-03 16:50 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +    <>
아래 div요소를 밖으로 옮기면서 최상위 태그가 필요해서 남겼습니다

2022-12-03 16:50 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +      console.log('i am', page);
삭제했습니다

2022-12-03 16:50 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
>  import { bootListMyPage } from '../../atoms/index';
삭제했습니다

2022-12-03 16:50 UTC, headring commented on client/src/components/Loading/Loading.tsx
> +    </div>
다른 프로젝트에서 className으로 스타일을 주던 것을 그대로 가지고 왔네요. div삭제하겠습니다

2022-12-03 16:50 UTC, headring commented on client/src/utils/api/forumAPI.ts
> +    console.log(res.data.pageInfo.totalPages);
콘솔로그 삭제했습니다

2022-12-03 16:51 UTC, headring commented on client/src/utils/api/forumAPI.ts
> +  posts: any,
setPost안에서 post 배열과 연결 시켜주려고 가져 왔습니다. 근데 삭제해도 진행이 되니 삭제하겠습니다

2022-12-03 16:55 UTC, headring commented on client/src/utils/api/forumAPI.ts
> +    setPosts((posts: any) => posts.concat(res.data.data));
이전 상태와 새로운 상태값이 구조분해되는 형태 `(prevState) => [...prevState, ...res.data.data]`로 진행했는데 이게 안 되서 이 구조를 그대로 따라하여 안의 내용만 바꿨습니다. 현재 이 형태를 지우면 맨 처음 리뷰의 post를 살려서 다시 불러와야 합니다.

2022-12-03 17:02 UTC, headring commented on client/src/components/MyPageContent/MyPageTable.tsx
> +    await setLoading(true);
삭제했습니다

2022-12-03 17:03 UTC, headring commented on client/src/components/Table/Table.style.ts
> +import { ContentWrapper } from './../../pages/Forum.style';
삭제했습니다

2022-12-03 17:03 UTC, headring commented on client/src/pages/BootCamp.tsx
> +    await setLoading(false);
삭제했습니다

2022-12-04 09:05 UTC, jwp9633 commented on client/src/utils/api/forumAPI.ts
> +    setPosts((posts: any) => posts.concat(res.data.data));
제가 여쭤본 것은 posts라는 상태를 함수로 변경하는 로직을 작성하신 이유입니다.

현재의 형태는 다음과 같습니다.
```ts
const func = (posts: any) => posts.concat(res.data.data);

setPosts(func);
```

posts라는 상태는 함수로 변경하지 않고, 새롭게 받아온 데이터로 변경해야 하는 것 아닌가요?

2022-12-04 09:05 UTC, jwp9633 commented on client/src/utils/api/forumAPI.ts
> +  posts: any,
아래 코멘트와 연관이 있는 것 같습니다.

2022-12-04 09:07 UTC, jwp9633 commented on client/src/components/Loading/Loading.tsx
> +    </div>
아직 삭제되지 않은 것 같습니다.

2022-12-04 09:15 UTC, jwp9633 commented on client/src/pages/BootCampDetail.tsx
> +          <a href={`${items.site}`} target="_blank" rel="noopener noreferrer">
네 알겠습니다.

2022-12-04 09:20 UTC, jwp9633 requested changes
스터디, 멘토링 게시판 전체 게시글 페이지에서 같은 내용이 2번 보여지고 있습니다. 확인 후 수정 부탁드리겠습니다.

2022-12-04 09:20 UTC, jwp9633 commented on client/src/components/Loading/Loading.tsx
>      </div>
div 요소는 아직 필요한가요?

2022-12-05 01:00 UTC, jwp9633 commented on client/src/utils/api/forumAPI.ts
> +    setPosts((posts: any) => posts.concat(res.data.data));
제가 몰랐던 기능이네요. 확인했습니다.

2022-12-05 01:06 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-12-05 01:09 UTC, merged