client-sanghyun: Feat/#250 auth routing
codestates-seb/seb40_main_027 pull request #258
Opened 2022-12-03 13:08 UTC by headring

인증이 필요한 라우팅(AuthRoute)
- 글쓰기 및 마이페이지

참고 [블로그](https://choisuhyeok.tistory.com/m/95)

2022-12-03 14:52 UTC, jwp9633 requested changes

2022-12-03 14:52 UTC, jwp9633 commented on client/src/App.tsx
> +        </Route>
path가 update인 것도 로그인 필요하니 여기로 옮겨 주시면 감사하겠습니다.

2022-12-03 14:52 UTC, jwp9633 commented on client/src/components/Route/AuthRoute.tsx
> +    </div>
div 요소로 감싼 이유가 있으실까요?

2022-12-03 17:07 UTC, headring commented on client/src/components/Route/AuthRoute.tsx
> +    </div>
단순히 코드를 옮겨온 거라서 삭제했습니다

2022-12-03 17:08 UTC, headring commented on client/src/App.tsx
> +        </Route>
path가 update인 것도 옮겼습니다

2022-12-04 00:22 UTC, jwp9633 approved these changes

2022-12-04 14:24 UTC, merged