client-yoonkyoung cssrefactor
codestates-seb/seb40_main_027 pull request #259
Opened 2022-12-03 15:33 UTC by skyhanull

2022-12-03 18:23 UTC, headring approved these changes
branch를 생성할 위치에서 먼저 git pull origin client 한번 부탁드립니다. 몇몇 코드가 옛날 거입니다.

2022-12-03 18:23 UTC, headring commented on client/src/pages/SignUp.style.tsx
> +        border-radius: 10px;
32번째 라인에서 정의한 4px border로 여기서도 4px이 나오는데 input쪽은 얇게 유지하는 것이 더 좋다고 생각합니다

2022-12-04 01:39 UTC, skyhanull commented on client/src/pages/SignUp.style.tsx
> +        border-radius: 10px;
git pull 하고 2px로 수정했습니다

2022-12-04 13:07 UTC, jwp9633 requested changes

2022-12-05 06:03 UTC, jwp9633 commented on client/src/pages/SignUp.style.tsx
> +    border-radius: 10px;
이 부분은 제 로컬에서만 문제있는 것 같아서 넘어가겠습니다.

2022-12-05 06:03 UTC, jwp9633 commented on client/src/pages/Login.style.ts
> +        border: 4px solid var(--greenMain);
이 부분은 제 로컬에서만 문제있는 것 같아서 넘어가겠습니다.

2022-12-05 06:14 UTC, jwp9633 requested changes

2022-12-05 06:14 UTC, jwp9633 commented on client/src/atoms/index.tsx
> +  key: 'upDateMyPage',
updateMyPage로 작성하는 것이 더 좋을 것 같습니다.

2022-12-05 06:14 UTC, jwp9633 commented on client/src/components/TestForm/TypeForm.tsx
> +  const imgList9 = <img src={testImg4} alt="적성검사 이미지" width="100%" height="100%" />;
이미지 파일명이 imgList 순서와 같으면 더 좋을 것 같습니다.

2022-12-05 06:14 UTC, jwp9633 commented on client/src/index.tsx
> +  </RecoilRoot>
React.StrictMode를 다시 넣는 것이 더 좋을 것 같습니다.

개발 시에만 오류를 잘 찾아내기 위해 2번 실행되고, 배포 시에는 1회만 실행되니 있는 것이 더 좋을 것 같습니다.

2022-12-05 06:14 UTC, jwp9633 commented on client/src/pages/SignUp.tsx
> +      {/* </S.Logoview> */}
주석을 남겨두신 이유가 있으실까요?

2022-12-05 06:45 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-12-05 06:53 UTC, merged