client-yoonkyoung: mainpage view구현
codestates-seb/seb40_main_027 pull request #51
Opened 2022-11-15 12:54 UTC by skyhanull

전체적인 view는 구현을 했는데 1920px일때 위주로 작업을 하려다보니 그냥 npm start할때 나오는 페이지와 구현이 좀 달라져서 좀 더 고쳐볼 생각입니다

2022-11-17 07:53 UTC, jwp9633 requested changes
리뷰 확인 부탁드립니다.

2022-11-17 07:53 UTC, jwp9633 commented on client/src/pages/Main.tsx
> +            적성검사
![Screenshot 2022-11-17 at 4 44 21 PM](https://user-images.githubusercontent.com/47207736/202386485-896c20b4-a49c-451c-a17a-331e5a2e3f4a.png)
![Screenshot 2022-11-17 at 4 46 07 PM](https://user-images.githubusercontent.com/47207736/202386629-a6f78ca9-93e7-4c61-9bbc-725ffd6b3359.png)

아이콘과 글자에 여백을 더 주면 어떨까요?

2022-11-17 07:53 UTC, jwp9633 commented on client/src/pages/Main.tsx
> +    height: 55%;
이미지에 가로와 세로를 모두 %로 주면 화면 크기에 따라 이미지가 왜곡되어 보일 수 있습니다.

width만 100% 주면 괜찮은 것 같은데, heigt 옵션은 삭제하는 게 어떨까요?

2022-11-17 07:53 UTC, jwp9633 commented on client/src/pages/Main.tsx
> +      width: 100%;
이미지에 가로와 세로를 모두 %로 주면 화면 크기에 따라 이미지가 왜곡되어 보일 수 있습니다.

width만 100% 주면 괜찮은 것 같은데, height 옵션은 삭제하는 게 어떨까요?

2022-11-17 07:53 UTC, jwp9633 commented on client/src/pages/Main.tsx
> +            <Icon icon="fluent:person-question-mark-16-regular" color="#1dca89" width="90" height="72" />
color 속성은 직접 string으로 주는 것보다 COLOR.TS에 있는 색상 변수를 사용하면 좋을 것 같습니다.

2022-11-17 08:50 UTC, skyhanull commented on client/src/pages/Main.tsx
> +            적성검사
<img width="1110" alt="스크린샷 2022-11-17 오후 5 49 22" src="https://user-images.githubusercontent.com/106054006/202399778-55f853da-b987-41bb-a4e9-f6ead9b5225e.png">
사진정도의 여백을 주었는데 이정도면 괜찮을까요?

2022-11-17 08:51 UTC, skyhanull commented on client/src/pages/Main.tsx
> +    height: 55%;
수정했습니다!

2022-11-17 08:51 UTC, skyhanull commented on client/src/pages/Main.tsx
> +            <Icon icon="fluent:person-question-mark-16-regular" color="#1dca89" width="90" height="72" />
수정했습니다!

2022-11-17 13:53 UTC, headring approved these changes
지금은 아니더라도 나중에 리팩토링할 때 한번 확인해주면 더 좋을 듯 합니다. 
고생하셨습니다 :)

2022-11-17 13:53 UTC, headring commented on client/src/pages/Main.tsx
> +
지금 줄어들면 이미지는 그대로인데 뒷배경만 줄어듭니다.
추후에 다시 리팩토링할 때 svg 태그를 작성하여 그 상위태그의 크기에 따라 줄어드는 방향으로 작성을 하면 더 좋을 것 같아요.

```
svg{
  width: 80%;
  height: 80%;
}
```
그러나 위와 같이 작성하게 되면 콘텐츠 글자와 사진이 일자로 정렬되기에 IconContent를 div로 전환시켜서 그 안에 있는 하위 tag를 inline-blcok 속성을 주는 것도 좋을 것 같습니다.

2022-11-17 13:53 UTC, headring commented on client/src/App.tsx
> +      <Footer />
현재 height 조정 시 footer가 바로 banner아래로 올라오고 있습니다.
이 부분은 나중에 리팩토링하면서 한번 더 봐주면 좋을 것 같아요

2022-11-17 15:04 UTC, skyhanull commented on client/src/pages/Main.tsx
> +
우선은 inline으로 하려니 작업해야 할 것이 많을 것 같아 아이콘의 비율을 %로 해서 비율이 줄을 때 같이 줄도록 조정을 해봤습니다!

2022-11-17 15:06 UTC, skyhanull commented on client/src/App.tsx
> +      <Footer />
이부분은 혹시 제 화면에선 안올라와서 혹시 내일 한번 화면을 보여주실 수 있으실까요

2022-11-18 00:19 UTC, jwp9633 requested changes

2022-11-18 00:19 UTC, jwp9633 commented on client/src/pages/Main.tsx
> +  /* vertical-align: middle; */
주석을 남겨두신 이유가 있으실까요?
사용할 예정이 없다면 지우는 것이 좋을 것 같습니다.

2022-11-18 00:43 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-18 00:44 UTC, skyhanull commented on client/src/pages/Main.tsx
> +  /* vertical-align: middle; */
주석 삭제 완료했습니다

2022-11-18 00:58 UTC, merged