clinet-sanghyun: Feat/#18 banner
codestates-seb/seb40_main_027 pull request #57
Opened 2022-11-16 05:14 UTC by headring

배너 작업 완료

필요 props
- text(string): 배너 가운데 글자 입력
- pageType(string): post OR other --> post는 게시판용 그림, 나머지는 그냥 그림

2022-11-16 08:53 UTC, jwp9633 requested changes
코멘트 확인 부탁드려요.

2022-11-16 08:53 UTC, jwp9633 commented on client/src/components/Banner/index.tsx
> +          <img src={pageType === 'post' ? boardimage : bootimage} alt="rightimg" />
alt 값을 `right-img`로 변경하는 것은 어떨까요?

2022-11-16 08:53 UTC, jwp9633 commented on client/src/styles/GlobalStyle.tsx
> +    --grayBanner: #EBE7E4;
grayBannerBackground로 네이밍하면 어떨까요?

그리고 src/assets/constant/COLOR.ts에서 추가 부탁드립니다.

2022-11-16 13:07 UTC, skyhanull commented
확인했습니다!

2022-11-16 18:16 UTC, headring commented on client/src/components/Banner/index.tsx
> +  .banner-inner {
재사용성을 위해서 하는 것은 말씀하신 대로 분리하는 것이 좋습니다. 
다만 저 banner-inner라는 것이 banner component 이외에 사용될 상황은 희박하다고 봅니다. 

그리고 seb repository들 확인한 결과 모든 것을 분리하는 [케이스](https://github.com/codestates-seb/seb39_pre_055/blob/main/client/src/pages/Edit/style.ts)와 현재처럼 진행하는 [케이스2](https://github.com/codestates-seb/seb39_main_019/blob/main/client/src/components/Button.jsx) 총 두 가지 케이스 모두 다 존재하기에 인터넷에서 찾아본 styled-components에 관한 [best-practice](https://www.robinwieruch.de/styled-components/) 내용 전달드립니다
간단하게 요약하자면:
- (대부분 선호)모든 스타일을 분리하면 조금 더 JS스럽게 작성 가능하며 '모든 것을 컴포넌트화' 가능
- (css 코드에 익숙한 사람들 선호)하나의 root에서 모든 것을 작성하면 css(extenstion 포함)의 이점과 JS 코드가 순수 HTML 태그와 같이 작성 가능

다만, 모든 스타일을 분리하실 거면 각 style.ts로 따로 css를 보관하는 것이 더 좋다고 봅니다.
한 파일 안에 변수 선언이 많으면서 코드가 길어질 경우 가독성이 더 떨어집니다.
(같은 best-practice 안에서도 style.ts로 따로 두는 것을 더 권장합니다. [다른 글](https://blog.cloudboost.io/separate-your-code-with-styled-components-ec4fd1ee3ef8)에서도 이와 같이 권정합니다)

2022-11-17 00:09 UTC, jwp9633 commented on client/src/components/Banner/index.tsx
> +  .banner-inner {
말씀하신 것처럼 두 방법 다 틀린 방법은 아닙니다.

제가 제안을 드렸던 이유는 banner-inner 뿐만 아니라 아래 대부분의 div 요소를 className으로 관리하셨기 때문입니다. 그럴 거면 다 스타일 컴포넌트를 적용하는 것과 코드 양에서 큰 차이가 없고 재사용성도 높일 수 있기 때문이죠.

현재 상황에서는 말씀하신 대로 div 요소들이 재사용될 가능성이 낮으니 className으로 작성하셔도 차이는 거의 없습니다. 그래서 제안만 드렸던 거에요. 어떤 스타일로 작성할지는 상현님 선택에 맞기겠습니다.

그리고 모든 스타일을 분리할 때도 style.ts로 따로 보관하는 방법도 있고, 한 파일에 보관하는 방법도 있는데요. 이는 팀의 성향에 따라 정하면 된다고 생각합니다. 저희는 처음에 한 파일에 보관하기로 했기 때문에 특이한 경우가 아니라면 한 파일에 보관하는 게 맞겠죠.

2022-11-17 00:50 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-17 00:50 UTC, headring commented on client/src/components/Banner/index.tsx
> +          <img src={pageType === 'post' ? boardimage : bootimage} alt="rightimg" />
변경했습니다

2022-11-17 00:50 UTC, headring commented on client/src/pages/Main.tsx
> +  );
변경했습니다

2022-11-17 00:50 UTC, headring commented on client/src/styles/GlobalStyle.tsx
> +    --grayBanner: #EBE7E4;
변경했습니다

2022-11-17 00:54 UTC, merged