client-yoonkyoung: mypage구현
codestates-seb/seb40_main_027 pull request #67
Opened 2022-11-17 00:34 UTC by skyhanull

2022-11-17 17:12 UTC, headring requested changes
확인했고 아래에 제 의견 추가했습니다.
혹시 제가 코드 문맥을 잘못 이해하여 작성한 것이 있다면 말씀부탁드릴게요.

2022-11-17 17:12 UTC, headring commented on client/src/components/MypageContent/MypageList.tsx
> +interface Dummy {
이미 54번째 라인부터 DummyData에 각 key value가 명확하여 여기서 Interface를 잡을 필요는 없는데 혹시 api를 보고 미리 잡아놓으신 걸까요?

2022-11-17 17:12 UTC, headring commented on client/src/components/MypageContent/Sidebar.tsx
> +  const [isco, setIsco] = useRecoilState(sidebarFloading);
혹시 isContent의 약자라면 camelCase가 더 좋지 않을까요?

2022-11-18 01:15 UTC, skyhanull commented on client/src/App.tsx
> +import MyPage from './pages/MyPage';
이름 수정했습니다!

2022-11-18 01:16 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +import styled from 'styled-components';
styled는 몰라도 pageheader는 사용이 필요한데 오류가 뜨나요??

2022-11-18 01:16 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +  const [currentTab, setCurrentTab] = useState<any>(0);
수정했습니다

2022-11-18 01:16 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +  const TabHandler = (id: any) => {
수정했습니다

2022-11-18 01:16 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +            {' '}
수정했습니다

2022-11-18 01:16 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +          <div>
요부분은 제가 삭제를 해봤는데 오류가 떠서 혹시 저 4줄 다말씀하시는 건가요?

2022-11-18 01:16 UTC, skyhanull commented on client/src/atoms/index.js
> +});
수정했습니다

2022-11-18 01:17 UTC, skyhanull commented on client/src/components/Button/LoginButton.tsx
> +interface clickType {
수정했습니다

2022-11-18 01:17 UTC, skyhanull commented on client/src/components/Header/MainHeader.tsx
> +        {/* <div>
주석 삭제했습니다

2022-11-18 01:17 UTC, skyhanull commented on client/src/components/MypageContent/MypageList.tsx
> +interface Dummy {
미리 잡아보려햇지만 문서보니 좀 다른거 같아 우선 삭제했습니다

2022-11-18 01:17 UTC, skyhanull commented on client/src/components/MypageContent/Sidebar.tsx
> +  const [isco, setIsco] = useRecoilState(sidebarFloading);
수정했습니다

2022-11-18 03:04 UTC, headring commented on client/src/pages/Mypage.tsx
> +import styled from 'styled-components';
제가 조금 더 구체적으로 이야기를 못 한 것 같네요. `styled`사용하지 않는다고 하니 삭제하면 더 좋을 것 같아요.

2022-11-18 03:11 UTC, headring commented on client/src/pages/Mypage.tsx
> +          <div>
이 부분은 제가 잘 못 본것 같네요 빈 div 태그가 하나 더 존재해서 감싸고 있는 것으로 착각했네요

2022-11-18 04:00 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +import styled from 'styled-components';
이부분 삭제했습니다!

2022-11-19 04:53 UTC, jwp9633 requested changes
코멘트 확인 부탁드립니다.

2022-11-19 04:53 UTC, jwp9633 commented on client/src/App.tsx
>        <Footer />
Footer 컴포넌트가 2개 들어가 있어서 1개는 삭제하는 게 좋을 것 같습니다.

2022-11-19 04:53 UTC, jwp9633 commented on client/src/App.tsx
> +      <div>
Routes를 div로 한 번 더 감싼 이유가 있으실까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/Header/MainHeader.tsx
>    const [islogin, setIslogin] = useState(true);
camelCase로 작성부탁드립니다.

`islogin` -> `isLogin`
`setIslogin` -> `setIsLogin`

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/Header/MainHeader.tsx
> +//onChange={clickLogin}
주석을 작성하신 이유가 있으실까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/MypageContent/SideBar.style.tsx
> +import styled from 'styled-components';
게시판에서도 Sidebar가 사용되기 때문에 파일 이름을 MyPageSideBar.tsx로 작성하는 것은 어떨까요?

그리고 여러 파일에서 Sidebar와 SideBar가 혼용되고 있는데, SideBar로 모두 통일하는 것은 어떨까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/MypageContent/SideBar.style.tsx
> +  .baov {
baov는 어디서 사용되는 클래스인가요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/MypageContent/SideBar.style.tsx
> +  @keyframes setMotionhide {
`setMotionhide`를 camelCase로 작성하면 어떨까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/components/MypageContent/Sidebar.tsx
> +        <S.SidebarPage className="hide-menu"></S.SidebarPage>
셀프 클로징으로 작성하면 어떨까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/pages/MyPage.style.tsx
> +  background-color: ${(props) => (props.className === 'tab-button' ? 'var(--greenMain)' : '#a9dbbd')};
#a9dbbd 색상을 COLOR.ts와 GlobalStyle.tsx에 선언하는 것은 어떨까요?

2022-11-19 04:53 UTC, jwp9633 commented on client/src/pages/Mypage.tsx
> +                // style={currentTab === el.id ?  : {}}
주석은 삭제하면 좋을 것 같습니다.

2022-11-19 06:26 UTC, skyhanull commented on client/src/components/Button/LoginButton.tsx
> +// import React from 'react';
수정했습니다

2022-11-19 06:26 UTC, skyhanull commented on client/src/components/Header/MainHeader.tsx
> +            </button>
수정했습니다

2022-11-19 06:27 UTC, skyhanull commented on client/src/components/Header/PageHeader.tsx
> +  const [iscollapse, setIscollapse] = useRecoilState(sidebarFloading);
수정했습니다

2022-11-19 06:29 UTC, skyhanull commented on client/src/components/Header/PageHeader.tsx
> +  .sidebar-pra {
삭제했습니다

2022-11-19 06:30 UTC, skyhanull commented on client/src/components/Header/PageHeader.tsx
> +  position: relative;
사이드바를 구현하다가 생긴것으로 지금은 필요없는 거라 삭제하겠습니다

2022-11-19 06:31 UTC, skyhanull commented on client/src/App.tsx
> +import MyPage from './pages/Mypage';
MyPage시 오류가 나서 Mypage로 통일했습니다

2022-11-19 06:31 UTC, skyhanull commented on client/src/App.tsx
>        <Footer />
삭제했습니다

2022-11-19 06:34 UTC, skyhanull commented on client/src/components/Header/MainHeader.tsx
>    const [islogin, setIslogin] = useState(true);
수정했습니다

2022-11-19 06:34 UTC, skyhanull commented on client/src/components/Header/MainHeader.tsx
> +//onChange={clickLogin}
수정했습니다

2022-11-19 06:40 UTC, skyhanull commented on client/src/components/MypageContent/SideBar.style.tsx
> +import styled from 'styled-components';
이 sidebar는 마이페이지에만 사용되는 것이 아니고 메인페이지의 헤더옆에 햄버거로 붙어있는 것이라 모든 페이지에 사용될거 같아서 게시판사이드바의 이름을 바꾸는게 더 좋지않을까요?
그리고 밑에는 보이는건 최대한 바꿔봤습니다 나중에 또 보인다면 말씀부탁드립ㅂ니다

2022-11-19 06:51 UTC, skyhanull commented on client/src/components/MypageContent/SideBar.style.tsx
> +  .baov {
현재는 sidebar-graypage로 바뀌었습니다

2022-11-19 06:52 UTC, skyhanull commented on client/src/components/MypageContent/SideBar.style.tsx
> +  @keyframes setMotionhide {
수정했습니다

2022-11-19 06:54 UTC, skyhanull commented on client/src/pages/MyPage.style.tsx
> +  background-color: ${(props) => (props.className === 'tab-button' ? 'var(--greenMain)' : '#a9dbbd')};
선언완료했습니다

2022-11-19 06:55 UTC, skyhanull commented on client/src/pages/Mypage.tsx
> +                // style={currentTab === el.id ?  : {}}
수정했습니다

2022-11-19 06:56 UTC, skyhanull commented on client/src/App.tsx
> +      <div>
우선 수정했습니다

2022-11-19 06:57 UTC, skyhanull commented on client/src/components/MypageContent/Sidebar.tsx
> +        <S.SidebarPage className="hide-menu"></S.SidebarPage>
이부분은 아마 다시 손 볼 것같아서 나중에 사이드바 완료시 다시 바꾸겠습니다

2022-11-19 09:34 UTC, headring approved these changes

2022-11-19 09:51 UTC, headring commented
고생하셨습니다! 따로 특이사항은 없습니다 :)

2022-11-19 14:22 UTC, jwp9633 requested changes
이전 리뷰에서 많은 코멘트를 남겼었는데 꼼꼼히 살펴보시고 반영해주셔서 감사합니다.
남은 코멘트들도 확인 부탁드리겠습니다.

2022-11-19 14:22 UTC, jwp9633 commented on client/src/App.tsx
> +import MyPage from './pages/Mypage';
현재 1개의 폴더 5개의 파일에서 `Mypage`라는 단어가 사용되는데, `Mypage`와 `MyPage`가 동시에 사용되고 있습니다.
두 단어를 한 단어로 통일해주셨으면 합니다.
제 생각에는 영어로 `mypage`보다 `my page`를 많이 사용하기 때문에 `MyPage`로 통일하는 것이 더 적절하다고 생각합니다.

폴더
- MypageContent

파일
- MyPageSchedule.style.tsx
- MypageList.tsx
- MypageSchedule.tsx
- MyPage.style.tsx
- Mypage.tsx

2022-11-19 14:22 UTC, jwp9633 commented on client/src/assets/constant/COLOR.ts
> +export const SUB_GREEN = '#a9dbbd';
기존에 선언된 변수들과 비슷하게 `GREEN_SUB`로 네이밍하는 것이 더 좋을 것 같습니다.

2022-11-19 14:22 UTC, jwp9633 commented on client/src/components/Header/MainHeader.tsx
> +//onChange={clickLogin}
수정이 안 된 것 같습니다.

2022-11-19 14:22 UTC, jwp9633 commented on client/src/components/MypageContent/SideBar.style.tsx
> +import styled from 'styled-components';
SideBar가 모든 페이지에 사용된다면,
현재의 MypageContent 폴더에 파일을 위치하는 것보다는 components에 SideBar라는 새폴더를 만들어서 컴포넌트를 작성하는 것이 더 좋을 것 같습니다.

그리고 말씀하신 오류는 저는 발생하지 않습니다. 그래서 어떤 오류인지 공유해주시면 같이 해결책을 찾아봐도 좋을 것 같습니다. 해결이 어렵다면 지금처럼 가야할 것 같네요.

2022-11-19 14:22 UTC, jwp9633 commented on client/src/components/MypageContent/Sidebar.tsx
> +        <S.SideBarPage className="hide-menu"></S.SideBarPage>
`hide-menu` 클래스는 사용하지 않는 것 같은데, 사용하지 않는다면 삭제 부탁드립니다.

2022-11-19 14:22 UTC, jwp9633 commented on client/src/styles/GlobalStyle.tsx
> +    --subgreen: #a9dbbd
`--greenSub`로 네이밍하면 더 좋을 것 같습니다.

2022-11-19 14:41 UTC, skyhanull commented on client/src/assets/constant/COLOR.ts
> +export const SUB_GREEN = '#a9dbbd';
수정했습니다

2022-11-19 14:42 UTC, skyhanull commented on client/src/components/MypageContent/Sidebar.tsx
> +        <S.SideBarPage className="hide-menu"></S.SideBarPage>
수정했습니다

2022-11-19 14:43 UTC, skyhanull commented on client/src/styles/GlobalStyle.tsx
> +    --subgreen: #a9dbbd
수정했습니다 그리고 위에 마이페이지에 대해 답변이 안되서 여기다가 적습니다 오류가 난 이유가 한글자 스펠링차이 수정은 아마 같은파일이 이미 있다고 생각해서 수정이 불가능한거 같아 삭제하고 다시 해서 수정완료했습니다 이건 다시한번 확인 부탁드립니다

2022-11-20 06:13 UTC, jwp9633 approved these changes
고생하셨습니다. 제가 수정한 것 한 번 확인 부탁드릴게요.

2022-11-20 06:21 UTC, merged