client-sanghyun: Feat/##53 loginpage
codestates-seb/seb40_main_027 pull request #72
Opened 2022-11-17 05:15 UTC by headring

로그인 페이지 작업 완료했습니다

추가적으로 banner 폴더에 저희가 의논한대로 css를 작성하였으니 참고 확인 부탁드리겠습니다

2022-11-17 08:45 UTC, jwp9633 requested changes
코멘트 확인 부탁드립니다.

2022-11-17 08:45 UTC, jwp9633 commented on client/src/components/Banner/banner.style.tsx
> +import styled from 'styled-components';
style.tsx 파일명은 해당 스타일이 적용되는 파일과 동일하게 네이밍하면 좋을 것 같습니다.

2022-11-17 08:45 UTC, jwp9633 commented on client/src/components/Banner/banner.style.tsx
> +export const Title = styled.div`
h2 요소를 사용하면 어떨까요?

2022-11-17 14:45 UTC, headring commented on client/src/components/Banner/banner.style.tsx
> +export const Title = styled.div`
reset css로 인하여 h2스타일코드를 기재했습니다

2022-11-18 00:12 UTC, jwp9633 commented on client/src/components/Banner/banner.style.tsx
> +export const Title = styled.div`
스타일 적용한 것 확인했습니다.

div 요소는 의미를 갖지 않지만 h2 요소는 두 번째 제목이라는 의미를 가지므로
저는 div 요소 대신 h2 요소를 사용하면 어떨까 제안드립니다.

2022-11-18 00:42 UTC, jwp9633 approved these changes
고생하셨습니다.

2022-11-18 00:47 UTC, skyhanull commented
확인했습니다!

2022-11-18 00:49 UTC, merged